-- 코드를 입력하세요
SELECT T1.AUTHOR_ID
, AUTHOR_NAME
, CATEGORY
, SUM((T1.PRICE * T3.SALES)) AS TOTAL_SALES
FROM BOOK AS T1 INNER JOIN AUTHOR AS T2 ON T1.AUTHOR_ID = T2.AUTHOR_ID
INNER JOIN BOOK_SALES AS T3 ON T1.BOOK_ID = T3.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;