-- 코드를 입력하세요
SELECT T1.ANIMAL_ID, T1.NAME
FROM ANIMAL_OUTS AS T1 LEFT JOIN ANIMAL_INS AS T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID
WHERE T2.ANIMAL_ID IS NOT NULL
ORDER BY T1.DATETIME - T2.DATETIME DESC
LIMIT 2;