-- 코드를 입력하세요
SELECT T1.FLAVOR
FROM ICECREAM_INFO T1 INNER JOIN FIRST_HALF T2
ON T1.FLAVOR = T2.FLAVOR
WHERE (T2.TOTAL_ORDER > 3000) AND (T1.INGREDIENT_TYPE = 'fruit_based')
ORDER BY T2.TOTAL_ORDER DESC;