-- 코드를 입력하세요
SELECT T1.ANIMAL_ID, T1.ANIMAL_TYPE, T1.NAME
FROM ANIMAL_OUTS AS T1 LEFT JOIN ANIMAL_INS AS T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID
WHERE T1.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered' AND T2.SEX_UPON_INTAKE REGEXP 'INTACT'
ORDER BY T1.ANIMAL_ID;