-- 코드를 입력하세요
SELECT USER_ID
, NICKNAME
, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소'
, CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4))
FROM USED_GOODS_USER AS T1 INNER JOIN USED_GOODS_BOARD AS T2
ON T1.USER_ID = T2.WRITER_ID
GROUP BY T2.WRITER_ID
HAVING COUNT(T2.WRITER_ID) >= 3
ORDER BY T1.USER_ID DESC;