-- 코드를 입력하세요
SELECT T1.REST_ID
, REST_NAME
, FOOD_TYPE
, FAVORITES
, ADDRESS
, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS T1 INNER JOIN REST_REVIEW AS T2
ON T1.REST_ID = T2.REST_ID
GROUP BY T2.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;