-- 코드를 입력하세요
SELECT T1.CATEGORY, SUM(T2.SALES) AS TOTAL_SALES
FROM BOOK AS T1 INNER JOIN BOOK_SALES AS T2
ON T1.BOOK_ID = T2.BOOK_ID
WHERE T2.SALES_DATE LIKE '2022-01%'
GROUP BY T1.CATEGORY
ORDER BY CATEGORY ASC;