-- 코드를 입력하세요
SELECT T2.APNT_NO
, T1.PT_NAME
, T1.PT_NO
, T2.MCDP_CD
, T3.DR_NAME
, T2.APNT_YMD
FROM PATIENT AS T1 INNER JOIN APPOINTMENT AS T2
ON T1.PT_NO = T2.PT_NO INNER JOIN DOCTOR AS T3
ON T2.MDDR_ID = T3.DR_ID
WHERE (DATE_FORMAT(T2.APNT_YMD, '%Y-%m-%d') = '2022-04-13')
AND (T2.MCDP_CD = 'CS')
AND (T2.APNT_CNCL_YN = 'N')
ORDER BY T2.APNT_YMD ASC;